service: aws-json-rules-example-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  determineFoulStatus:
    handler: handler.endpoint
    events:
      - http:
          path: player
          method: get
